version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/example_user
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  postgres_db:
